name: Deploy Infrastructure

on:
#    push:
#     branches: 
#       - main
#    pull_request:
#     branches:
#       - main
env:
  WORKSPACE: test
  BUCKET: abc-kishore
  REGION: us-east-1 
  

jobs:
  deploy:
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
          role-to-assume: arn:aws:iam::439547845933:role/openid-role
          aws-region: us-east-1
          role-session-name: abcdefgh
    - name: Install Terraform
      uses: hashicorp/setup-terraform@v1
    - name: Download S3 Object
      run: aws s3 cp s3://abc-kishore/${WORKSPACE}.tfvars tf.tfvars
    - name: Initialize Terraform
      run: |
        terraform init -backend-config="bucket=${BUCKET}" -backend-config="key=${WORKSPACE}.tfstate" -backend-config="region=${REGION}"
        terraform workspace list
        terraform workspace select ${WORKSPACE}
       
      continue-on-error: true
    - name: SELECT workspace
      run: |
        terraform workspace new ${WORKSPACE}
      continue-on-error: true
    
    - name: Plan Terraform changes
      run: terraform plan -var-file=tf.tfvars -lock=false

    - name: Apply Terraform changes
      run: terraform apply -auto-approve -var-file=tf.tfvars
