name: Deploy Infrastructure

on:
  workflow_dispatch:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: us-east-1

    - name: Install Terraform
      uses: hashicorp/setup-terraform@v1
    - name: Download S3 Object
      run: aws s3 cp s3://abc-kishore/stage.tfvars tf.tfvars
    - name: Initialize Terraform
      run: terraform init -backend-config="bucket=abc-kishore" -backend-config="key=kk/terraform.tfstate" -backend-config="region=us-east-1"
    - name: create workspace
      run: terraform workspace new stage
    
    - name: Plan Terraform changes
      run: terraform plan -var-file=tf.tfvars

    - name: Apply Terraform changes
      run: terraform apply -auto-approve -var-file=tf.tfvars
